# Generated by Django 4.2.1 on 2025-08-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=250, verbose_name='Текст вопроса')),
            ],
            options={
                'ordering': ['-create_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(verbose_name='Пользователь')),
                ('text', models.CharField(max_length=250, verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='application.question')),
            ],
            options={
                'ordering': ['-create_at'],
                'abstract': False,
            },
        ),
    ]
